name: "Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - gh_actions_workflow

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:	
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: 'us-west-2'

    steps:
      - uses: actions/checkout@v2
      - name: Create buckets
        run: |
          aws s3 ls
          bash create_backend_bucket.sh
          bash create_job_bucket.sh
